meinersite/homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('datenschutzerklaerung/', views.Privacy.as_view(), name='privacy'),
    path('impressum/', views.Imprint.as_view(), name='imprint'),
]

meinersite/meinersite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

meinersite/homepage/models.py
from django.db import models

# Create your models here.

meinersite/homepage/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class Index(TemplateView):
    template_name = 'homepage/index.html'

class Privacy(TemplateView):
    template_name = 'homepage/privacy.html'

class Imprint(TemplateView):
    template_name = 'homepage/imprint.html'

meinersite/homepage/templates/homepage/imprint.html
{% extends 'base.html' %}
{% block title %}Impressum{% endblock title %}
{% block main %}
            <h1>Impressum</h1>
            <h2>Kontaktdaten</h2>
            <p>Lorenz Zahn<br>Saalberg 1<br>06110 - Halle (Saale)</p>

            <p>Telefon: 0345/2905446<br>E-Mail: <a href="mailto:webmaster@lorenz-zahn.de">webmaster@lorenz-zahn.de</a></p>

            <h2>Hinweis</h2>
            <p>Diese Website ist ein öffentlicher Auftritt einer Privatperson. Es ist kein komerzieller Zweck vorgesehen.</p>
        {% endblock main %}

meinersite/homepage/templates/homepage/index.html
{% extends 'base.html' %}
{% block title %}Hauptseite{% endblock %}
        {% block main %}
            <h1>Hier entsteht eine neue Website!</h1>
            <p>Das hier kaum etwas ist, ist ein Stückweit Absicht. Diese Seite dient als Spielplatz und wird über die kommenden Monate weiterentwickelt.</p>
        {% endblock %}

meinersite/homepage/templates/homepage/privacy.html
{% extends 'base.html' %}
{% block title %}Datenschutzerklärung{% endblock title %}
        {% block main %}
            <h1>Datenschutzerklärung</h1>
            <p>Die Nutzung dieser Website kann mit der Verarbeitung von personenbezogenen Daten verbunden sein. Damit diese Verarbeitungen für Sie nachvollziehbar sind, möchte ich Ihnen mit den folgenden Informationen einen Überblick zu diesen Verarbeitungen verschaffen. Um eine faire Verarbeitung zu gewährleisten, möchte ich Sie außerdem über Ihre Rechte nach der Europäischen Datenschutz-Grundverordnung (DSGVO) und dem Bundesdatenschutzgesetz (BDSG) informieren.</p>

            <h2>Namen und Kontaktdaten des Verantwortlichen</h2>
            <p>Wenn Sie Fragen oder Anregungen zu diesen Informationen haben oder sich wegen der Geltendmachung Ihrer Rechte an mich wenden möchten, richten Sie Ihre Anfrage bitte an:</p>

            <p>Lorenz Zahn<br>Saalberg 1<br>06110 - Halle (Saale)</p>
            <p>Telefon: 0345/2905446<br>E-Mail: <a href="mailto:webmaster@lorenz-zahn.de">webmaster@lorenz-zahn.de</a></p>

            <h2>Allgemeine Angaben zur Datenverarbeitung, Rechtsgrundlagen und Speicherdauer</h2>
            <h3>Allgemeine Angaben zur Datenverarbeitung</h3>
            <p>Ich verarbeite personenbezogene Daten unter Beachtung der einschlägigen Datenschutzvorschriften, insbesondere der DSGVO und des BDSG. Eine Datenverarbeitung durch mich findet nur auf der Grundlage einer gesetzlichen Erlaubnis statt. Bei der Nutzung dieser Website werden personenbezogene Daten nur mit Ihrer Einwilligung (Art. 6 Abs. 1 Buchst. a) DSGVO), zur Erfüllung eines Vertrags, dessen Vertragspartei Sie sind, oder auf Ihre Anfrage zur Durchführung vorvertraglicher Maßnahmen (Art. 6 Abs. 1 Buchst. b) DSGVO), zur Erfüllung einer rechtlichen Verpflichtung (Art. 6 Abs. 1 Buchst. c) DSGVO) oder wenn die Verarbeitung zu Wahrung meiner berechtigten Interessen oder den berechtigten Interessen eines Dritten erforderlich ist, sofern nicht Ihre Interessen oder Grundrechte und Grundfreiheiten, die den Schutz personenbezogener Daten erfordern, überwiegen (Art. 6 Abs. 1 Buchst. f) DSGVO) verarbeitet.</p>

            <h3>Dauer der Speicherung</h3>
            <p>Sofern sich aus den folgenden Hinweisen nichts anderes ergibt, werden die Daten nur solange, wie es zur Erreichung des Verarbeitungszwecks oder für die Erfüllung der vertraglichen oder gesetzlichen Pflichten erforderlich ist gespeichert. Solche gesetzlichen Aufbewahrungspflichten können sich insbesondere aus handels- oder steuerrechtlichen Vorschriften ergeben.</p>

            <h2>Datenverarbeitung durch Provider und Host</h2>
            <p>Diese Website wird auf einen angemieteten virtuellen Server gehostet. Anbieter dieses ist die Strato AG, Pascalstraße 10, 10587 Berlin (nachfolgend : "Strato"). Wenn sie meine Website besuchen, erfasst Strato verschiedene Daten inklusive ihrer IP-Adresse. Die Verwendung von Strato erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO.</p>
            <p>Weitere Informationen können Sie der <a target="_blank" href="https://www.strato.de/datenschutz/">Datenschutzerklkärung von Strato</a> entnehmen.
            <p>Ich habe einen Vertrag über Auftragsverarbeitung (AVV) mit Strato geschlossen. Hierbei handelt es sich um einen datenschutzrechtlich vorgeschriebenen Vertrag, der gewährleistet, dass dieser die personenbezogenen Daten nur nach meinen Weisungen und unter Einhaltung der DSGVO verarbeitet.</p>

            <h2>Automatisierte Datenverarbeitung des Servers</h2>
            <h3>Verarbeitung von Server-Log-Files</h3>
            <p>Bei der rein informativen Nutzung unserer Website werden zunächst automatisiert (also nicht über eine Registrierung) allgemeine Informationen gespeichert, die Ihr Browser an meinen Server übermittelt. Hierzu zählen standardmäßig: Browsertyp/ -version, verwendetes Betriebssystem, aufgerufene Seite, die zuvor besuchte Seite (Referrer URL), IP-Adresse, Datum und Uhrzeit der Serveranfrage und HTTP-Statuscode. Die Verarbeitung erfolgt zur Wahrung meines berechtigten Interesse und beruht auf der Rechtsgrundlage des Art. 6 Abs. 1 Buchst. f) DSGVO. Diese Verarbeitung dient der technischen Verwaltung und der Sicherheit der Website. Die gespeicherten Daten werden gelöscht, wenn nicht aufgrund konkreter Anhaltspunkte ein berechtigter Verdacht auf eine rechtswidrige Nutzung besteht und eine weitere Prüfung und Verarbeitung der Informationen aus diesem Grund erforderlich ist.</p>

            <h2>Datenverarbeitung durch Nutzerangaben</h2>
            <p>Diese Seite verwendet ein Kontaktforumular. Die durch dieses übermittelten personenbezogenen Daten werden gespeichert, bis diese durch mich verarbeitet wurden und danach gelöscht. (In der Regel nach spätestens nach 7 bis 14 Tage.)</p>

            <h2>Cookies, Tracking, Plugins, externe Inhalte</h2>
            <h3>Cookies</h3>
            <p>Diese Website verwendet Cookies. Bei Cookies handelt es sich um kleine Textdateien, die durch Ihren Browser gespeichert werden, wenn Sie eine Website besuchen. Hierdurch wird der verwendete Browser gekennzeichnet und kann durch meinen Webserver wiedererkannt werden. Dabei werden ausschließlich sitzungsbasierte Cookies („Session Cookies“) verwendet. Diese Cookies sind für den sicheren Betrieb notwendig und werden automatisiert nach einer vorgegebenen Dauer oder schließen des Browsers gelöscht. Sofern es durch diese Verwendung von Cookies zu einer Verarbeitung personenbezogener Daten kommt, beruht diese auf der Rechtsgrundlage des Art. 6 Abs. 1 Buchst. f) DSGVO. Sie können die Cookies in den Sicherheitseinstellungen Ihres Browsers jederzeit löschen. Sie können der Verwendung von Cookies durch Ihre Browsereinstellungen grundsätzlich widersprechen.</p>

            <h2>Rechte der Betroffenen, Beschwerderecht</h2>
            <h3>Ihre Rechte</h3>
            <p>Als betroffene Person haben Sie das Recht, mir gegenüber Ihre Betroffenenrechte geltend zu machen. Dabei haben Sie insbesondere die folgenden Rechte:</p>

            <ul>
                <li>Sie haben nach Maßgabe des Art.15 DSGVO und § 34 BDSG das Recht, Auskunft darüber zu verlangen, ob und gegebenenfalls in welchen Umfang wir personenbezogene Daten zu Ihrer Person verarbeiten oder nicht.</li>
                <li>Sie haben das Recht, nach Maßgabe des Art. 16 DSGVO von uns die Berichtigung Ihrer Daten zu verlangen</li>
                <li>Sie haben das Recht, nach Maßgabe des Art. 17 DSGVO und § 35 BDSG von uns die Löschung Ihrer personenbezogenen Daten zu verlangen.</li>
                <li>Sie haben das Recht, nach Maßgabe des Art. 18 DSGVO die Verarbeitung Ihrer personenbezogenen Daten einschränken zu lassen.</li>
                <li>Sie haben das Recht, nach Maßgabe des Art. 20 DSGVO die Sie betreffenden personenbezogenen Daten, die Sie uns bereitgestellt haben, in einem strukturierten, gängigen und maschinenlesbaren Format zu erhalten, und diese Daten einem anderen Verantwortlichen zu übermitteln.</li>
                <li>Sie haben nach Maßgabe des Art. 21 Abs. 1 DSGVO das Recht, gegen jede Verarbeitung, die auf der Rechtsgrundlage des Art. 6 Abs. 1 Buchst. e) oder f) DSGVO beruht, Widerspruch einzulegen. Sofern durch uns personenbezogene Daten über Sie zum Zweck der Direktwerbung verarbeitet werden, können Sie gegen diese Verarbeitung gem. Art. 21 Abs. 2 und Abs. 3 DSGVO Widerspruch einlegen.</li>
            </ul>

            <p>Sofern Sie uns eine gesonderte Einwilligung in die Datenverarbeitung erteilt haben, können Sie diese Einwilligung nach Maßgabe des Art. 7 Abs. 3 DSGVO jederzeit widerrufen. Durch einen solchen Widerruf wird die Rechtmäßigkeit der Verarbeitung, die bis zum Widerruf aufgrund der Einwilligung erfolgt ist, nicht berührt.</p>

            <h3>Beschwerde bei einer Aufsichtsbehörde</h3>
            <p>Wenn Sie der Ansicht sind, dass eine Verarbeitung der Sie betreffenden personenbezogenen Daten gegen die Bestimmungen der DSGVO verstößt, haben Sie nach Maßgabe des Art. 77 DSGVO das Recht auf Beschwerde bei einer Aufsichtsbehörde.</p>

            <p><em>Diese Datenschutzerklärung basiert auf einem Muster bereitgestellt durch die <a target="_blank" href="https://www.datenschutzkanzlei.de/datenschutzerklaerung/">Datenschutzkanzlei</a>. (Stand: 19. August 2021, 11:05)</em></p>
        {% endblock main %}

meinersite/templates/base.html
<!DOCTYPE html>
<html lang="de-DE">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock title %} | LORENZ ZAHN</title>
        <meta name="author" content="Lorenz Zahn">
        <meta name="description" content="Dies ist der öffentliche Auftritt von Lorenz Zahn. Ein kleiner Spielplatz für Webinhalte und Entwicklung dieser.">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="shortcut icon" href="{% static 'favicon.svg' %}" type="image/svg+xml" sizes="any">
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body>
        <header>{% block header %}{% endblock header %}</header>
        <nav>{% block nav %}
            <a href="{% url 'homepage:index' %}">Hauptseite</a>
        {% endblock nav %}</nav>
        <main>{% block main %}{% endblock main %}</main>
        <footer>{% block footer %}
            <a href="{% url 'homepage:privacy' %}">Datenschutzerklärung</a>
            <a href="{% url 'homepage:imprint' %}">Impressum</a>
            <a target="_blank" href="https://github.com/Fereon/meiner-sites">Quellcode auf Github</a>
        {% endblock footer %}</footer>
    </body>
</html>